
before_script:
  - php -v
  - composer -v
  - composer install

atoum:
  stage: test
  script: ./vendor/bin/atoum
  coverage: '/Code coverage value: \d+\.\d+%/'

  artifacts:
    reports:
      junit: atoum.xunit.xml

  cache:
    paths:
      - vendor/
